added -J option to exclude collector peers by ASN
CAIDA/libbgpstream pull request #225
Opened 2022-02-01 02:35 UTC by albertodainotti

This filter allows the user to exclude collector peers specified by their ASN

2022-02-01 16:48 UTC, alistairking requested changes
Couple minor nits here, but otherwise it seems fine.

At a high level I would prefer adding logic so that we could negate existing filters rather than explicitly adding them like this.
I.e., it wouldn't ever be useful to provide `-j 1234 -J 5678` (right?) so it'd be nice to be able to repurpose the existing peer ASN filtering machinery instead.

2022-04-16 01:50 UTC, albertodainotti commented on lib/datainterfaces/bsdi_broker.c
> +  // not peer asns
Oops.

2022-04-16 01:50 UTC, albertodainotti commented on tools/bgpreader.c
> +  {{"peer-asn", required_argument, 0, 'J'},
Oops again

2022-04-16 13:20 UTC, alistairking approved these changes
lgtm

2022-04-16 13:20 UTC, merged